### ISSUE TITLE
要输入api的都无法使用

### ISSUE THREAD

**Issue by Nande741** [Noisyfox/ACT.FFXIVTranslate#10]
[上午 03:52:12] (InvalidApiKey)ACT.FFXIVTranslate.translate.TranslateException: Invalid API key
   於 ACT.FFXIVTranslate.translate.bing.BingTranslateProvider.GetAuthToken()
   於 ACT.FFXIVTranslate.translate.bing.BingTranslateProvider.Translate(List`1 chattingLines)
   於 ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)

[上午 03:52:37] (InvalidApiKey)ACT.FFXIVTranslate.translate.TranslateException: Invalid API key
   於 ACT.FFXIVTranslate.translate.bing.BingTranslateProvider.GetAuthToken()
   於 ACT.FFXIVTranslate.translate.bing.BingTranslateProvider.Translate(List`1 chattingLines)
   於 ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)

[上午 03:52:52] (ApiLimitExceed)ACT.FFXIVTranslate.translate.TranslateException: Exceeded the daily limit on the amount of translated text
   於 ACT.FFXIVTranslate.translate.yandax.YandaxTranslateProvider.Translate(List`1 chattingLines)
   於 ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)

[上午 03:52:54] (ApiLimitExceed)ACT.FFXIVTranslate.translate.TranslateException: Exceeded the daily limit on the amount of translated text
   於 ACT.FFXIVTranslate.translate.yandax.YandaxTranslateProvider.Translate(List`1 chattingLines)
   於 ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)

[上午 03:53:18] (GeneralServiceError)ACT.FFXIVTranslate.translate.TranslateException: Unknown Error Code
   於 ACT.FFXIVTranslate.translate.baidu.BaiduTranslateProvider.Translate(List`1 chattingLines)
   於 ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)

[上午 03:53:19] (GeneralServiceError)ACT.FFXIVTranslate.translate.TranslateException: Unknown Error Code
   於 ACT.FFXIVTranslate.translate.baidu.BaiduTranslateProvider.Translate(List`1 chattingLines)
   於 ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)

原本已经使用一个月了 用百度都很正常
今天就无法使用了
也试着用其他的翻译 只有google 有效
其他都无效果

**Comment by Noisyfox** [comment]
我这周末看看

**Comment by Nande741** [comment]
一直都是使用百度..
昨天就无法用了 也检查过key
过个几天再试试 谢谢

**Comment by beckyeeky** [comment]
Google 的是不是也过期了（

**Comment by Nande741** [comment]
(GeneralServiceError)ACT.FFXIVTranslate.translate.TranslateException: Unknown Error Code
   於 ACT.FFXIVTranslate.translate.baidu.BaiduTranslateProvider.Translate(List`1 chattingLines)
   於 ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)

确认key没输入错 都跳这个错误..
目前除了百度 其他使用正常 那应该是我百度key有问题了吗

**Comment by Noisyfox** [comment]
> Google 的是不是也过期了（

Google 非官方api还可以用

**Comment by Noisyfox** [comment]
> (GeneralServiceError)ACT.FFXIVTranslate.translate.TranslateException: Unknown Error Code
> 於 ACT.FFXIVTranslate.translate.baidu.BaiduTranslateProvider.Translate(List`1 chattingLines)
> 於 ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)
> 
> 确认key没输入错 都跳这个错误..
> 目前除了百度 其他使用正常 那应该是我百度key有问题了吗

我这里百度翻译可以用呀
