### ISSUE TITLE
插件翻译失效，不翻译游戏内内容

### ISSUE THREAD

**Issue by Zeeroz** [Noisyfox/ACT.FFXIVTranslate#13]
插件版本1.3.1.105
只能相应剪切板的内容翻译，却无法翻译游戏内的对话
但是在插件日志中间却能正常显示游戏内的对话内容
尝试使用了谷歌翻译/yandex翻译，都无效

![image](https://user-images.githubusercontent.com/38998206/74529861-ae215c80-4f63-11ea-8ec4-83f482c08d50.png)
![image](https://user-images.githubusercontent.com/38998206/74529878-ba0d1e80-4f63-11ea-9855-7c987fcef86d.png)
![image](https://user-images.githubusercontent.com/38998206/74530257-972f3a00-4f64-11ea-9fbd-27e7cd9c3ca2.png)

**Comment by Noisyfox** [comment]
code=003d 代表的是NPC对话，频道设置里默认是没有选中的，所以不会翻译。

**Comment by Zeeroz** [comment]
> code=003d 代表的是NPC对话，频道设置里默认是没有选中的，所以不会翻译。

哦~感谢，终于搞懂了。
之前重新设置了防火墙还用不了就很奇怪，现在搞懂了
