### ISSUE TITLE
Overlay is displayed at startup even if "show overlay" is unchecked

### ISSUE THREAD

**Issue by Seferex** [Noisyfox/ACT.FFXIVTranslate#14]
Hello, first of all thank you so much for all your effort on making this plugin!

When i open ACT, the plugin window will be displayed even if i did untick the "show overlay"... It will disappear if i will tick it on/ff again... 
Hope you will fix it on next release!

P.S. Is it possible to have an option for japanese where it shows also the "pronunce"? For example the word こんにちは will be translated to "hello" + "Kon'nichiwa"
Or since it would not be so nice to see, add an option to just show only "hello" or only "Kon'nichiwa".

**Comment by Noisyfox** [comment]
Thanks for you report! I'll make a fix ASAP.

There is a issue (#5) that requests the rōmaji. I'd like to add this however I can't find a free online service that provides this with an easy to use API so I can't give you any promise.

**Comment by Seferex** [comment]
Thank you for the quick reply.

I will look for next release ^^ and lets hope you will find a free way to implement the romajis! 

Thanks again many and many times for the very nice plugin!

**Comment by Noisyfox** [comment]
Version 1.4.1 has been released that should fix this issue.

**Comment by Seferex** [comment]
wow! i did not expect such a quick fix! 

Thank you a lot! You rock!.

Hope you will find a way to add romajis, then this plugin will be more than perfect! (atm is already 10/10!). Thanks!
