### ISSUE TITLE
The interface does not switch from Chinese to English.

### ISSUE THREAD

**Issue by garry78** [Noisyfox/ACT.FFXIVTranslate#15]
<img width="521" alt="1" src="https://user-images.githubusercontent.com/9497965/77252957-667ba800-6c68-11ea-9bad-59d88bc0ce99.png">
The plugin ignores the selected interface language - English, and remains in Chinese. Deleted, put different versions, nothing helps.

**Comment by Noisyfox** [comment]
https://github.com/Noisyfox/ACT.FFXIVTranslate/wiki/How-to-Install-&-Change-Plugin-Language#3-copy-to-destination
