### ISSUE TITLE
I am not able to use Microsoft translator

### ISSUE THREAD

**Issue by Seferex** [Noisyfox/ACT.FFXIVTranslate#18]
Hello,

i got my 2 keys for microsoft translator, but both keys seem to not work with it :(
I get this message on logs:

[18:35:15] (InvalidApiKey)ACT.FFXIVTranslate.translate.TranslateException: Invalid API key
   in ACT.FFXIVTranslate.translate.microsoft.MicrosoftTranslateProvider.GetAuthToken()
   in ACT.FFXIVTranslate.translate.microsoft.MicrosoftTranslateProvider.Translate(List`1 chattingLines)
   in ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)

Any ideas?
I am not able to generate for free any key in other places... And google unofficial stop working very quickly T_T

EDIT: It seems that microsoft translator has been updated recently (v3), may be the reason?

**Comment by duchuule** [comment]
I found out that the region of your resource needs to be Global for the key to work.

**Comment by Seferex** [comment]
Oh thats great!
By any chance, do you have an idea on how to set that? Im not very confident on that...
If not, i will just try to figure out by myself. Its already very nice that you found out what the problem is
