### ISSUE TITLE
Unable to change UI to English

### ISSUE THREAD

**Issue by reiszrie** [Noisyfox/ACT.FFXIVTranslate#19]
I was unable to change UI to English despite selecting English in the setting and restarting ACT. 

I'm using the latest version of ACT & ACT.FFXIVTranslate

Thank you

**Comment by Noisyfox** [comment]
Have you put the en-US folder at the same folder of the ACT main executable?

**Comment by reiszrie** [comment]
thanks! that fixed the issue.
