### ISSUE TITLE
Can not add the dll

### ISSUE THREAD

**Issue by BlanknessWhite** [Noisyfox/ACT.FFXIVTranslate#21]
---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.ArgumentException - 空路径名是非法的。
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)

   在 ACT.FFXIVTranslate.LogReadThread.DoWork(String logFilePath)

   在 ACT.FoxCommon.core.BaseThreading`1.WorkingThreadFunc(Object context)

   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   在 System.Threading.ThreadHelper.ThreadStart(Object obj)

System.IO.FileStream, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
---------------------------
确定   
---------------------------

**Comment by Noisyfox** [comment]
你添加了FFXIV解析插件没

**Comment by Noisyfox** [comment]
或者试一下 https://github.com/Noisyfox/ACT.FFXIVTranslate/releases/tag/1.6.0

**Comment by BlanknessWhite** [comment]
> 或者试一下 https://github.com/Noisyfox/ACT.FFXIVTranslate/releases/tag/1.6.0

好的,謝謝
