### ISSUE TITLE
Google translate

### ISSUE THREAD

**Issue by tokawa3b3333** [Noisyfox/ACT.FFXIVTranslate#22]
你好，我用google的有以下问题弹出了这个
(UnknownError)ACT.FFXIVTranslate.translate.TranslateException: 已發生類型 'ACT.FFXIVTranslate.translate.TranslateException' 的例外狀況。 ---> System.Net.Http.HttpRequestException: 回應狀態碼未表示成功: 429 (Too Many Requests)。
   於 System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   於 ACT.FFXIVTranslate.translate.google_unofficial.GoogleTranslateProvider.Translate(List`1 chattingLines)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 ACT.FFXIVTranslate.translate.google_unofficial.GoogleTranslateProvider.Translate(List`1 chattingLines)
   於 ACT.FFXIVTranslate.translate.TranslateService.TranslateThread.DoWork(TranslateContext context)
我有尝试自行申请Api key但同样失败
还是说那个key是输入方式不对?
用公用的api也同样有这问题
谢谢

**Comment by Noisyfox** [comment]
非官方Google翻译API本身就不保证可用性， (Too Many Requests) 基本意思就是白嫖谷歌被发现了，一般等一段时间就能用。
至于自行申请Key的是什么错误日志
