### ISSUE TITLE
不知道老板还有没有关注,这次好像不兼容6.0的解析插件了

### ISSUE THREAD

**Issue by tlatixat** [Noisyfox/ACT.FFXIVTranslate#24]
剪切板的等一些功能没问题,不过貌似读取不到游戏内聊天文本.
不知道是不是这次解析插件没有设置的问题

**Comment by Noisyfox** [comment]
解析插件更新了吗？

**Comment by tlatixat** [comment]
> 解析插件更新了吗？

老板,呆萌的那个更新了,能够解析数据了,只是不知道是不是先行放出的.

**Comment by Noisyfox** [comment]
怪事，我研究下

**Comment by SuSpoiled** [comment]
1.6也许是解析插件的问题，因为呆萌的ACT测试版解析插件更新之前还能用，更新后就不能了。

**Comment by Noisyfox** [comment]
咦？我这里可以加载的呀，你解析插件版本号是多少哦

**Comment by tlatixat** [comment]
> 咦？我这里可以加载的呀，你解析插件版本号是多少哦

2.6.2 
现在情况是1.6版本的翻译因为不明原因没办法读取到游戏内聊天文本,但是其他功能照常,剪切板也能实时发现并翻译.
然后我换了1.5版本的就莫名能够识别了聊天框文本了,不知道是哪里出了问题.

**Comment by Noisyfox** [comment]
发现问题了

试一下这个版本看看能不能用
https://ci.appveyor.com/api/buildjobs/0jys6efmsw5f8236/artifacts/ACT.FFXIVTranslate-1.6.0.127-Release.7z

**Comment by tlatixat** [comment]
> 发现问题了
> 
> 试一下这个版本看看能不能用 https://ci.appveyor.com/api/buildjobs/0jys6efmsw5f8236/artifacts/ACT.FFXIVTranslate-1.6.0.127-Release.7z

可以正常使用了,老板辛苦.
