### ISSUE TITLE
Translation on Russian

### ISSUE THREAD

**Issue by garry78** [Noisyfox/ACT.FFXIVTranslate#3]
Hi! Please chat translation on Russian language. Thanks in advance.

**Comment by Noisyfox** [comment]
You mean to translate other language to Russian?

**Comment by garry78** [comment]
Yes. I do not know English so well, and there are times when I do not understand what they write to me in the chat.

**Comment by Noisyfox** [comment]
Cool. I'll add Russian support in the next release.

**Comment by garry78** [comment]
Thank you!

**Comment by Noisyfox** [comment]
Please try v1.1.3

**Comment by garry78** [comment]
Russian has appeared. I'll check work in the evening, when I return home from work. The first time the plug-in is run, an error occurs.
![error](https://user-images.githubusercontent.com/9497965/31120265-7796b014-a83c-11e7-9b07-f71279e15152.JPG)

**Comment by Noisyfox** [comment]
I'll do a quick fix of that error.

**Comment by garry78** [comment]
Everything is working! Thank you very much!
