### ISSUE TITLE
希望悬浮窗高度可以调至200单位以下

### ISSUE THREAD

**Issue by Hoshiyuu** [Noisyfox/ACT.FFXIVTranslate#4]
希望悬浮窗高度可以调至200单位以下，个人用法比较偏向就显示3-4行。

**Comment by Noisyfox** [comment]
emmm之前是因为微软对窗口有个最小尺寸的限制，于是我就设置了一个差不多的大小。
我改下看看能不能弄小点。

**Comment by Hoshiyuu** [comment]
开发辛苦了，小题外问问，

那下巴我估计是放Powered by Yandex等翻译提供者使用声明的后遗症吧？
在用谷歌翻译的情况下能不能让窗口的下巴的空位再小些？比较容易整体上镶入游戏界面...

麻烦的话就不要紧了用起来不碍事 owob

**Comment by Noisyfox** [comment]
之前的窗口有个白色额头用来拖动 + 显示翻译版权信息，现在用更好的界面代替了，应该是可以调小高度限制

**Comment by Noisyfox** [comment]
我把限制设置成了40x40，应该够小了23333

**Comment by Hoshiyuu** [comment]
够小了ｗｗｗ
