### ISSUE TITLE
Google Translate & glossary

### ISSUE THREAD

**Issue by Bluefissure** [Noisyfox/ACT.FFXIVTranslate#8]
很多物品名/技能/动作/NPC名字似乎可以用glossary来定义
资源文件可以从[ffxiv-datamining](https://github.com/viion/ffxiv-datamining)和[ffxiv-datamining-cn](https://github.com/thewakingsands/ffxiv-datamining-cn)同步
相关文档：[glossary](https://cloud.google.com/translate/docs/glossary)

似乎v3beta没有提供.NET的SDK，我跑了
添加一个custom翻译服务如何（

**Comment by Bluefissure** [comment]
查看了几家API，都比较贵，限制也比较多，溜了溜了

**Comment by Noisyfox** [comment]
google cloud translator v3 最坑的地方是身份认证不支持API key而要用那个坑爹的 OAuth2 json文件。。。 翻译API接口倒是很简单我都已经自己实现好了，然而那个认证搞不定。。。

**Comment by Bluefissure** [comment]
> google cloud translator v3 最坑的地方是身份认证不支持API key而要用那个坑爹的 OAuth2 json文件。。。 翻译API接口倒是很简单我都已经自己实现好了，然而那个认证搞不定。。。

我看到了，beta没有.net SDK，身份认证要用client……有点麻烦

**Comment by Noisyfox** [comment]
而那个v2 api虽然能直接用API Key但是没有免费额度 。。。所以我就一直没发布带google translator的版本。。。虽然代码早就写好了哈哈哈哈哈
